import SiteHeader from './components/SiteHeader'
import getSiteHeader from "@/app/libs/getSiteHeader";
import StyledComponentsRegistry from './libs/registry'
import './global.css'


export const metadata = {
    title: 'Jules Carluccio',
    description: 'Generated by create next app',
}

const RootLayout = async ({children}) => {
    const siteHeader = await getSiteHeader;
    return (
        <html lang="fr">
        <body>
        <SiteHeader siteHeaderData={siteHeader.data}/>
        <StyledComponentsRegistry>
            {children}
        </StyledComponentsRegistry>
        </body>
        </html>
    )
}

export default RootLayout;

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
