import {Inter} from 'next/font/google'
import SiteHeader from './components/SiteHeader'


const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Jules Carluccio',
    description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
    return (
        <html lang="fr">
        <body className={inter.className}>
        <SiteHeader/>
        {children}
        <foooter>Layout footer</foooter>
        </body>
        </html>
    )
}

export default RootLayout;

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
