import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jules Carluccio',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
)

export default RootLayout;

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }